# -*- coding: utf-8 -*-
"""EX-2 Logistic Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMEU1SxWgWdwlKkhST5oG769UY3MOUFZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# Load dataset
df = pd.read_csv('HepatitisCdata.csv')

# Drop unnamed index column
df = df.drop(columns=["Unnamed: 0"])

# Encode target: "0=Blood Donor" -> 0, others -> 1 (Hepatitis)
df['Target'] = df['Category'].apply(lambda x: 0 if 'Blood Donor' in x else 1)

# Encode 'Sex' column: 'm' -> 0, 'f' -> 1
df['Sex'] = df['Sex'].map({'m': 0, 'f': 1})

# Drop original 'Category' column
df = df.drop(columns=['Category'])

# Drop rows with missing values
df = df.dropna()

# Features and target
X = df.drop(columns=['Target'])
y = df['Target']

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Confusion matrix and report
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Plot confusion matrix
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Blood Donor', 'Hepatitis'],
            yticklabels=['Blood Donor', 'Hepatitis'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Logistic Regression')
plt.tight_layout()
plt.show()